<footer>
      <hr />
      <p>Team members:</p>
      <a href="mailto:103602069@student.swin.edu.au">Charlotte McMenamin</a> |
      <a href="mailto:103985456@student.swin.edu.au">Lana Tilli</a> |
      <a href="mailto:104004802@student.swin.edu.au">Connor Mitchell</a> |
      <a href="mailto:103619881@student.swin.edu.au">Jack Hannah</a> |
      <a href="mailto:103070417@student.swin.edu.au">Jae Fehring</a>
</footer>